title = "Red Polygon"
languageCode = "en-us"
baseurl = "http://www.redpolygon.net/"
theme = "landing-page-hugo"
[params]
    description = ""
    googleAnalytics = "UA-92630737-1"
[[params.social]]
    title = "twitter"
    icon = "twitter"
    url = "https://twitter.com/icecreammatt"
[[params.social]]
    title = "email"
    icon = "envelope-o"
    url = "mailto:contact@redpolygon.net"
